development:
  adapter: postgresql
  encoding: unicode
  database: scripture_search_development
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: scripture_search_test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: scripture_search_production
  username: postgres
  password: postgres
